#!/bin/env /bin/bash

#docker run --rm -it  --network none -v `pwd`:/mnt/shared manualbuild.localhost/zsa-qmk /bin/bash
#docker run --rm -it  --network none -v `pwd`:/mnt/shared manualbuild.localhost/zsa-qmk bash /mnt/shared/run-make

case "$1" in
	"ergodox")
		echo "building ergodox firmware"
		docker run --rm -it --network none \
			-v `pwd`:/mnt/shared \
			jonberenguer/zsa-qmk bash /mnt/shared/run-make-ergodox_ez
		;;
	"planck")
		echo "building planck firmware"
		docker run --rm -it --network none \
			-v `pwd`:/mnt/shared \
			jonberenguer/zsa-qmk bash /mnt/shared/run-make-planck_ez_glow
		;;
	*)	echo "selections: ergodox,planck" ;;
esac

# wally dir must be included in PATH
wally &
